package com.monitoreo.modelo;

// Generated 8/07/2013 08:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Auditoria generated by hbm2java
 */
@Entity
@Table(name = "auditoria", schema = "public")
public class Auditoria implements java.io.Serializable {

	private int audid;
	private Usuarios usuarios;
	private Date fecha;
	private String direccionip;

	public Auditoria() {
	}

	public Auditoria(int audid, Usuarios usuarios) {
		this.audid = audid;
		this.usuarios = usuarios;
	}

	public Auditoria(int audid, Usuarios usuarios, Date fecha,
			String direccionip) {
		this.audid = audid;
		this.usuarios = usuarios;
		this.fecha = fecha;
		this.direccionip = direccionip;
	}

	@Id
	@Column(name = "audid", unique = true, nullable = false)
	public int getAudid() {
		return this.audid;
	}

	public void setAudid(int audid) {
		this.audid = audid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarios_usuaid", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "direccionip")
	public String getDireccionip() {
		return this.direccionip;
	}

	public void setDireccionip(String direccionip) {
		this.direccionip = direccionip;
	}

}
