package com.monitoreo.modelo;

// Generated 8/07/2013 08:40:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Direccionesip generated by hbm2java
 */
@Entity
@Table(name = "direccionesip", schema = "public")
public class Direccionesip implements java.io.Serializable {

	private int direcid;
	private Usuarios usuarios;
	private Estados estados;
	private String direccion;

	public Direccionesip() {
	}

	public Direccionesip(int direcid, Usuarios usuarios, Estados estados,
			String direccion) {
		this.direcid = direcid;
		this.usuarios = usuarios;
		this.estados = estados;
		this.direccion = direccion;
	}

	@Id
	@Column(name = "direcid", unique = true, nullable = false)
	public int getDirecid() {
		return this.direcid;
	}

	public void setDirecid(int direcid) {
		this.direcid = direcid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarios_usuaid", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estados_estadoid", nullable = false)
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	@Column(name = "direccion", nullable = false)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

}
