package com.monitoreo.modelo;

// Generated 8/07/2013 08:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados", schema = "public")
public class Estados implements java.io.Serializable {

	private int estadoid;
	private String descripcion;
	private int puertosPuertoid;
	private Set<Direccionesip> direccionesips = new HashSet<Direccionesip>(0);
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);
	private Set<Puertos> puertoses = new HashSet<Puertos>(0);

	public Estados() {
	}

	public Estados(int estadoid, int puertosPuertoid) {
		this.estadoid = estadoid;
		this.puertosPuertoid = puertosPuertoid;
	}

	public Estados(int estadoid, String descripcion, int puertosPuertoid,
			Set<Direccionesip> direccionesips, Set<Usuarios> usuarioses,
			Set<Puertos> puertoses) {
		this.estadoid = estadoid;
		this.descripcion = descripcion;
		this.puertosPuertoid = puertosPuertoid;
		this.direccionesips = direccionesips;
		this.usuarioses = usuarioses;
		this.puertoses = puertoses;
	}

	@Id
	@Column(name = "estadoid", unique = true, nullable = false)
	public int getEstadoid() {
		return this.estadoid;
	}

	public void setEstadoid(int estadoid) {
		this.estadoid = estadoid;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "puertos_puertoid", nullable = false)
	public int getPuertosPuertoid() {
		return this.puertosPuertoid;
	}

	public void setPuertosPuertoid(int puertosPuertoid) {
		this.puertosPuertoid = puertosPuertoid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Direccionesip> getDireccionesips() {
		return this.direccionesips;
	}

	public void setDireccionesips(Set<Direccionesip> direccionesips) {
		this.direccionesips = direccionesips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Puertos> getPuertoses() {
		return this.puertoses;
	}

	public void setPuertoses(Set<Puertos> puertoses) {
		this.puertoses = puertoses;
	}

}
