package com.monitoreo.modelo;

// Generated 20/06/2013 10:19:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Monitoreos generated by hbm2java
 */
@Entity
@Table(name = "monitoreos", schema = "public")
public class Monitoreos implements java.io.Serializable {

	private int moniid;
	private Usuarios usuarios;
	private String puerto;
	private Integer puertonombre;
	private String estadoencontrado;
	private Date fecha;

	public Monitoreos() {
	}

	public Monitoreos(int moniid, Usuarios usuarios) {
		this.moniid = moniid;
		this.usuarios = usuarios;
	}

	public Monitoreos(int moniid, Usuarios usuarios, String puerto,
			Integer puertonombre, String estadoencontrado, Date fecha) {
		this.moniid = moniid;
		this.usuarios = usuarios;
		this.puerto = puerto;
		this.puertonombre = puertonombre;
		this.estadoencontrado = estadoencontrado;
		this.fecha = fecha;
	}

	@Id
	@Column(name = "moniid", unique = true, nullable = false)
	public int getMoniid() {
		return this.moniid;
	}

	public void setMoniid(int moniid) {
		this.moniid = moniid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usuarios_usuaid", nullable = false)
	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	@Column(name = "puerto")
	public String getPuerto() {
		return this.puerto;
	}

	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

	@Column(name = "puertonombre")
	public Integer getPuertonombre() {
		return this.puertonombre;
	}

	public void setPuertonombre(Integer puertonombre) {
		this.puertonombre = puertonombre;
	}

	@Column(name = "estadoencontrado")
	public String getEstadoencontrado() {
		return this.estadoencontrado;
	}

	public void setEstadoencontrado(String estadoencontrado) {
		this.estadoencontrado = estadoencontrado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
