package com.monitoreo.modelo;

// Generated 20/06/2013 10:19:10 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Puertos generated by hbm2java
 */
@Entity
@Table(name = "puertos", schema = "public")
public class Puertos implements java.io.Serializable {

	private int puertoid;
	private Estados estados;
	private String nombre;
	private String puerto;

	public Puertos() {
	}

	public Puertos(int puertoid, Estados estados) {
		this.puertoid = puertoid;
		this.estados = estados;
	}

	public Puertos(int puertoid, Estados estados, String nombre, String puerto) {
		this.puertoid = puertoid;
		this.estados = estados;
		this.nombre = nombre;
		this.puerto = puerto;
	}

	@Id
	@Column(name = "puertoid", unique = true, nullable = false)
	public int getPuertoid() {
		return this.puertoid;
	}

	public void setPuertoid(int puertoid) {
		this.puertoid = puertoid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estados_estadoid", nullable = false)
	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "puerto")
	public String getPuerto() {
		return this.puerto;
	}

	public void setPuerto(String puerto) {
		this.puerto = puerto;
	}

}
