package com.monitoreo.modelo;

// Generated 8/07/2013 08:40:16 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "public")
public class Roles implements java.io.Serializable {

	private int rolid;
	private String roldescripcion;
	private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

	public Roles() {
	}

	public Roles(int rolid, String roldescripcion) {
		this.rolid = rolid;
		this.roldescripcion = roldescripcion;
	}

	public Roles(int rolid, String roldescripcion, Set<Usuarios> usuarioses) {
		this.rolid = rolid;
		this.roldescripcion = roldescripcion;
		this.usuarioses = usuarioses;
	}

	@Id
	@Column(name = "rolid", unique = true, nullable = false)
	public int getRolid() {
		return this.rolid;
	}

	public void setRolid(int rolid) {
		this.rolid = rolid;
	}

	@Column(name = "roldescripcion", nullable = false)
	public String getRoldescripcion() {
		return this.roldescripcion;
	}

	public void setRoldescripcion(String roldescripcion) {
		this.roldescripcion = roldescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<Usuarios> getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set<Usuarios> usuarioses) {
		this.usuarioses = usuarioses;
	}

}
